### ISSUE TITLE
internal server error when creating a user with an email that was already used

### ISSUE THREAD

**Issue by guyver2** [guyver2/battlechess#9]
When creating a user with a username and email. if the username is already taken we get a meaningful error message.
But if the email is already taken, the returned value is not so great...

![image](https://user-images.githubusercontent.com/576461/116459123-b6627080-a865-11eb-9480-a6f4ccb604e8.png)

**Comment by quimnuss** [comment]
@Geniedesalpages do you want to tackle this bug to get acquainted? Create a test that proves de bug and then a fix?

**Comment by guyver2** [comment]
solved
